version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
    - "8080:80"
    volumes:
     - ./nginx_config/nginx.conf:/etc/nginx/conf.d/default.conf
     - ./dist:/data/www
