version: "3.9"

services:
  server:
    container_name: server
    image: server
    build:
      context: ./packages/server/
      dockerfile: Dockerfile.server
    restart: always
    depends_on:
      - client
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "SERVER_PORT=${SERVER_PORT}"
    ports:
      - '3100:3100'
    networks:
      - portfolio

  client:
    container_name: client
    image: client
    build:
      context: ./packages/client/
      dockerfile: Dockerfile.client
    volumes:
      - dist:/app/dist

  db:
    container_name: portfolio_db
    image: postgres
    ports:
      - "3011:5432"
    restart: always
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    networks:
      - portfolio


  nginx:
    container_name: nginx
    image: nginx
    restart: always
    depends_on:
      - server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - dist:/data/www
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    networks:
      - portfolio

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html

volumes:
  etc-letsencrypt:
  www-html:
  dist:

networks:
  portfolio:
    name: portfolio
