version: "3"
services:
  db:
    container_name: portfolio_db
    image: postgres
    ports:
      - "3011:5432"
    restart: always
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=Arthurs15"
      - "POSTGRES_DB=portfolio_db"
