version: "3"
services:
  db:
    container_name: portfolio_db
    image: postgres
    ports:
      - "3011:5432"
    restart: always
    environment:
      - "POSTGRES_USER=&{POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"

